### ISSUE TITLE
Test to confirm operation of individual APIs

### ISSUE THREAD

**Issue by jbest** [Gene-Weaver/VoucherVision#1]
It took me multiple tries to get my Google API to work because I wasn't looking closely at the terminal output when running the default "Test PaLM2" process. The only feedback in the GUI was that the tests failed. Once I looked at the terminal output, I saw first that I needed to enable Google Cloud Vision on the project I had created. Then I saw that I needed to enable billing on that project. It would be helpful if the API Keys configuration page had a Test button for each API so that could be clicked to confirm the API key was set up correctly and the access, billing, etc. was all functioning. Bonus would be to report specific errors in the GUI because in error message in the terminal there was a URL directly to the project and billing pages I needed to go to in order to fix the problems.

**Comment by Gene-Weaver** [comment]
Great feedback. I'll write some tests that show up on the API Keys configuration page to make things more unified.

**Comment by Gene-Weaver** [comment]
Added individual tests for all API keys on the setup page. Note - the Google Vision OCR key still must be added first.
