### ISSUE TITLE
Documentation update: can the necessary API keys be set as environment variables?

### ISSUE THREAD

**Issue by nickynicolson** [Gene-Weaver/VoucherVision#2]
Scanning through the readme to determine if the vouchervision application could be configured to run on huggingface spaces. This would require specification of API keys (as documented here https://github.com/Gene-Weaver/VoucherVision#setting-up-api-key) as secrets (which are then made available as environment variables). Is this possible?

**Comment by Gene-Weaver** [comment]
Great question. Yes, they can be set as environment variables. Coincidentally, we are nearly ready to make our huggingface spaces implementation public. When it is, you can [find it here](https://huggingface.co/spaces/phyloforfun/VoucherVision). I'll drop a message here when it's public, it should be this week.

**Comment by Gene-Weaver** [comment]
Alright, we have a [prototype version running on HF Spaces](https://huggingface.co/spaces/phyloforfun/VoucherVision). Please let me know if you find any bugs or have feature/improvement requests! Feel free to duplicate the space if you want to use your own API keys (we are providing access to some APIs until the end of 2023).
