### ISSUE TITLE
Fix for Gemini 1.5 Pro, Gemini 1.0 pro

### ISSUE THREAD

**Issue by mickley** [Gene-Weaver/VoucherVision#20]
These models both currently fail because of an issue with the API key. 

I traced it to model_maps.py get_version_has_key(). Remove the space after "Pro ". and then "Gemini 1.5 Pro" will match and things run correctly:
https://github.com/Gene-Weaver/VoucherVision/blob/74f9d4970ba803c247ca49a576500e03d1b3f27c/vouchervision/model_maps.py#L161

**Comment by Gene-Weaver** [comment]
Thanks James!
