### ISSUE TITLE
Error Creating Desktop Shortcut (Windows)

### ISSUE THREAD

**Issue by jlramirez** [Gene-Weaver/VoucherVision#43]
When executing **python create_desktop_shortcut.py**, the following error occurs:

Traceback (most recent call last):
  File "C:\Users\vh\desktop\VoucherVision\create_desktop_shortcut.py", line 2, in <module> import win32com.client
  ModuleNotFoundError: No module named 'win32com'

Error occurs because the pywin32 package, which includes win32com.client, is not installed in Python environment. 
**pip install pywin32** resolved issue.

Resolution: Add pywin32 to the requirements.txt file to ensure the necessary module is installed.

**Comment by Gene-Weaver** [comment]
I forgot to add this to the VoucherVision instructions, I'll copy that part from the Editor instructions
